##   threenine.co.uk WordPress docker compose

version: '3'
services:
  wordpress:
    depends_on:
      - db
    image: wordpressdebugcustom:php7.3
    restart: always
    volumes:
      - ./html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: password12@
      XDEBUG_CONFIG: remote_host={your ip}       # Insert the IP of your host machine
    ports:
      - 80:80 # Expose http and https
      - 443:443
    networks:
      - back
  db:
    image: mysql:5.7
    restart: always
    volumes:
       - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password12@
    networks:
      - back
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password12@
    networks:
      - back
networks:
  back:
volumes:
  db_data: